### ISSUE TITLE
Licensing terms for the forums

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/core-team#15]
Some objections on URLO summarized by Niko here: https://users.rust-lang.org/t/tos-updated-to-match-rfcs-and-rust-repository/45650/27

Niko to discuss with Mozilla Legal again.

**Comment by nikomatsakis** [comment]
Update: There was some pushback about the appropriate licensing for users. I posted a [summary](https://users.rust-lang.org/t/tos-updated-to-match-rfcs-and-rust-repository/45650/27?u=nikomatsakis) here. The main point is that:

* People may post snippets of code when asking questions without being aware of the "terms of service", and they may not be aware that they are licensing the code in any particular way beyond "able to be seen on the forum".

I discussed this a bit with some folks from Mozilla legal but I have to summarize the feedback. One thought we had was to add an extra clause like "code snippets or other quotations that have a clearly identified source are licensed under the terms of that source", so that if people e.g. post a bit of code from a GPL source, it will not imply MIT/Apache-2 licensing. 

Some observations from the core team meeting today (I'm summarizing this after the fact, so they may not be quite accurate):

* Do we want to split the internals/users forums terms? Seems like it's asking for more confusion and trouble. Perhaps more subtle than it's worth, and it's not clear that the content of posts on the two forums are *that* different.
* Bottom line is that there will always be some responsibility -- we wanted to update the terms to favor people who copy things out from posts, primarily into RFCs but also possibly other sources, on the assumption that most people don't post things onto discussion boards that are meant to stay private. This puts the onus then onto posters to take care. But we can adopt some common clarifications (e.g., the "licensing for code snippets and quotations") to cover most cases.
* Expectation is that this is highly unlikely to matter in practice, since people usually post small, abstract snippets, so the change that somebody posts something that is large enough to matter, large enough to be worth copying, and it's not obvious that something fishy is going on, seems pretty small. But then again, laws exist to cover edge cases.

**Comment by aidanhs** [comment]
"there will always be some responsibility" - elaborating on this point to reference back, people both paste into and copy from forums, often without thinking about either. Whatever we do, one group of people will need to do more work

**Comment by emilyalbini** [comment]
@nikomatsakis drafted a comment and he's running it through Mozilla Legal for feedback. We're leaning to keep the current setup with an extra line that says if something is copied from a cited source, then it retains the license of that source. To make things more clear we'll try to provide examples in the posted comment.

**Comment by steveklabnik** [comment]
Niko's on vacation, no updates

**Comment by nikomatsakis** [comment]
[Posted the comment](https://users.rust-lang.org/t/tos-updated-to-match-rfcs-and-rust-repository/45650/29?u=nikomatsakis)

**Comment by carols10cents** [comment]
I think this can be closed now. Reopen if I'm wrong!
