### ISSUE TITLE
Governance WG checkin

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/core-team#9]
Item on the agenda in which @nikomatsakis reports to the rest of the Core Team what the Governance WG has been working on in the past week.

*Item added by before we transitioned to this issue tracker for our agenda.*

**Comment by nikomatsakis** [comment]
We had a meeting today ([transcript](https://zulip-archive.rust-lang.org/223182wggovernance/02100Meeting20200723.html)). One of the interesting things was that we were thinking we should try a "new style" of interaction where we would try to go to teams, ask questions, formulate a proposal for some kind of policy or other thing, and then bring it back to them for further iteration. i.e., take on the tedious work of writing policy in an effort to get things documented and clarified, and we thought that we might start by looking at just figuring out *what each team does* (starting with compiler/libs, since those are changing).

**Comment by emilyalbini** [comment]
No update as there was no Governance WG meeting this week.

**Comment by steveklabnik** [comment]
No updates this week.

**Comment by steveklabnik** [comment]
On hiatus this week due to rustconf.

**Comment by steveklabnik** [comment]
No updates this week.

**Comment by steveklabnik** [comment]
possibly taking a hiatus for a month, but also, working on charters for different teams. libs team has been really helpful here.

**Comment by steveklabnik** [comment]
Hiatus is official.

**Comment by nikomatsakis** [comment]
Relevant update is the libs team governance RFC:

https://github.com/rust-lang/rfcs/pull/2979

I believe this was partly done in conjunction with governance WG, but regardless it's in the theme :)

**Comment by Mark-Simulacrum** [comment]
Josh and Niko are iterating some more on the lang team staging procedure and interested in talking to libs to try to make procedures fairly uniform across the project.

**Comment by Manishearth** [comment]
This WG doesn't exist anymore in practice
